package Pacman;

import java.awt.geom.Point2D;

public class SimpleMazeBoard extends Board{

	SimpleMazeBoard(){
		super();
		super.boarddata = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDDDDDDDDDDDDDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDDDDWWDDDDWWDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDWWDDDD DDDDDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDDDDWWWWWWWWDDDDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDDDDDDDDDDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDDDDDDDWWDDDDDDDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDDDDDDD DDDDDDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW";
		for(int g = Ghost.GHOST_PINKY; g <= Ghost.GHOST_CLYDE; g++) {
			ghosts[g].setPosition(new Point2D.Double(-1,-1));
		}
		super.initGrids();
	}
	
	public void updateGhosts() {
		ghosts[Ghost.GHOST_BLINKY].move();
	}
	public void setMode(byte modeScatter, int ghost) {
		if (ghost == Ghost.GHOST_BLINKY) {
			ghosts[ghost].setMode(modeScatter);
		}
	}
	public void setModes(byte modeScatter) {
		ghosts[Ghost.GHOST_BLINKY].setMode(modeScatter);
	}	
}