package Pacman;

import java.awt.geom.Point2D;

public class SimpleMazeBoard extends Board{

	SimpleMazeBoard(){
		super();
		super.boarddata = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDDDDDDDDDDDDDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDDDDWWDDDDWWDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDWWDDDD DDDDDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDDDDWWWWWWWWDDDDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDDDDDDDDDDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDWWDWWWWWWWWDWWDWWWWWWWWWWWWDDDDDDDWWDDDDDDDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDWWWWWDWWDWWWWWDWWWWWWWWWWWWDDDDDDD DDDDDDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW";
		for(int g = Ghost.PINKY; g <= Ghost.CLYDE; g++) {
			ghosts[g].setPosition(new Point2D.Double(-1,-1));
		}
		super.initGrids();
	}
	
	public void updateGhosts() {
		ghosts[Ghost.BLINKY].move();
	}
	public void setMode(Ghost.Mode modeScatter, int ghost) {
		if (ghost == Ghost.BLINKY) {
			ghosts[ghost].setMode(modeScatter);
		}
	}
	public void setModes(Ghost.Mode modeScatter) {
		ghosts[Ghost.BLINKY].setMode(modeScatter);
	}	
}