package Pacman;

import java.awt.geom.Point2D;

public class SquareBoard extends Board{

	SquareBoard(){
		super();
		super.boarddata = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDDDDDDDDDDDDDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDDDDDDD DDDDDDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW";
/*		super.boarddata = "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWDDDDDDDDDDDDDDWWWWWW" +
						  "WWWWWWWWDWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDDDWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDWWWWWWWWWWWWWWDWWWWWW" +
						  "WWWWWWDDDDDDD DDDDDDDDWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW" +
						  "WWWWWWWWWWWWWWWWWWWWWWWWWWWW";*/
		for(int g = Ghost.BLINKY; g <= Ghost.CLYDE; g++) {
			ghosts[g].setPosition(new Point2D.Double(-1, -1));
		}
		super.initGrids();
	}
	
	public void updateGhosts() {}
	public void setMode(byte modeScatter, int ghost) {}
	public void setModes(byte modeScatter) {}
}