package Pacman;

import java.awt.geom.Point2D;

public class SquareBoard extends Board{

	SquareBoard(){
		super();
		super.boarddata = "WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWDDDDDDDDDDDDDDDDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDWWWWWWWWWWWWWWDWWWWWWWWWWWWDDDDDDD DDDDDDDDWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW";
		for(int g = Ghost.GHOST_BLINKY; g <= Ghost.GHOST_CLYDE; g++) {
			ghosts[g].setPosition(new Point2D.Double(-1, -1));
		}
		super.initGrids();
	}
	
	public void updateGhosts() {}
	public void setMode(byte modeScatter, int ghost) {}
	public void setModes(byte modeScatter) {}
}